####################################
###  パラメータ設定ファイル            ###
####################################

### カメラ設定
[Param]
sigma = 0.01
data_path = "../data/point_0023.pcd"
param_R = 0.02
param_K = 30
